#!/usr/bin/env perl
# $Id$

use PFL::Getoptv;
use strict;
use warnings;

my $d = "/local";
my $ud = "/usr/local";

my $p = ".psc.edu";
my $t = ".psc.teragrid.org";

my %dep = (
	arc => [
		{ prog => "slashd", host => "illusion1$p", dir => $d },
		{ exec => "sleep", arg => [2] },

		{ prog => "mount_slash", host => "firehose1$p",		   dir => $d,  arg => "-U /arc" },
		{ prog => "mount_slash", host => "firehose2$p",		   dir => $d,  arg => "-U /arc" },
		{ prog => "mount_slash", host => "firehose3$p",		   dir => $d,  arg => "-U /arc" },
		{ prog => "mount_slash", host => "firehose4$p",		   dir => $d,  arg => "-U /arc" },
		{ prog => "mount_slash", host => "kollman3$p",		   dir => $d,  arg => "-U /arc", init => 'modprobe fuse' },
		{ prog => "mount_slash", host => "xfer-admin$p",	   dir => $ud, arg => "-U /arc", init => 'modprobe fuse' },
		{ prog => "mount_slash", host => "tahini$p",		   dir => $ud, arg => "-U /arc", init => 'modprobe fuse' },
		{ prog => "mount_slash", host => "tg-login1.blacklight$t", dir => $d,  arg => "-U /arc" },
		{ prog => "mount_slash", host => "tg-login2.blacklight$t", dir => $d,  arg => "-U /arc" },

		{ exec => "sleep", arg => [2] },

		{ name => "sliod-ue", prog => "sliod", host => "tahini$p", dir => $ud, env => { CTL_SOCK_FILE => "/var/run/sliod.ue.sock", LNET_NETWORKS => "tcp12(eth2)" } },
		{ name => "sliod-uo", prog => "sliod", host => "tahini$p", dir => $ud, env => { CTL_SOCK_FILE => "/var/run/sliod.uo.sock", LNET_NETWORKS => "tcp12(vlan100)" } },

		{ name => "sliod0", prog => "sliod", host => "sense0$p", dir => $ud, env => { CTL_SOCK_FILE => "/var/run/sense0-sliod0.sock", LNET_NETWORKS => "tcp12(vlan100:0)" } },
		{ name => "sliod1", prog => "sliod", host => "sense0$p", dir => $ud, env => { CTL_SOCK_FILE => "/var/run/sense0-sliod1.sock", LNET_NETWORKS => "tcp12(vlan100:1)" } },
		{ name => "sliod2", prog => "sliod", host => "sense0$p", dir => $ud, env => { CTL_SOCK_FILE => "/var/run/sense0-sliod2.sock", LNET_NETWORKS => "tcp12(vlan100:2)" } },
		{ name => "sliod3", prog => "sliod", host => "sense0$p", dir => $ud, env => { CTL_SOCK_FILE => "/var/run/sense0-sliod3.sock", LNET_NETWORKS => "tcp12(vlan100:3)" } },
		{ name => "sliod4", prog => "sliod", host => "sense0$p", dir => $ud, env => { CTL_SOCK_FILE => "/var/run/sense0-sliod4.sock", LNET_NETWORKS => "tcp12(vlan100:4)" } },
		{ name => "sliod5", prog => "sliod", host => "sense0$p", dir => $ud, env => { CTL_SOCK_FILE => "/var/run/sense0-sliod5.sock", LNET_NETWORKS => "tcp12(vlan100:5)" } },
		{ name => "sliod6", prog => "sliod", host => "sense0$p", dir => $ud, env => { CTL_SOCK_FILE => "/var/run/sense0-sliod6.sock", LNET_NETWORKS => "tcp12(vlan100:6)" } },

		{ name => "sliod0", prog => "sliod", host => "sense1$p", dir => $ud, env => { CTL_SOCK_FILE => "/var/run/sense0-sliod0.sock", LNET_NETWORKS => "tcp12(vlan100:0)" } },
		{ name => "sliod1", prog => "sliod", host => "sense1$p", dir => $ud, env => { CTL_SOCK_FILE => "/var/run/sense0-sliod1.sock", LNET_NETWORKS => "tcp12(vlan100:1)" } },
		{ name => "sliod2", prog => "sliod", host => "sense1$p", dir => $ud, env => { CTL_SOCK_FILE => "/var/run/sense0-sliod2.sock", LNET_NETWORKS => "tcp12(vlan100:2)" } },
		{ name => "sliod3", prog => "sliod", host => "sense1$p", dir => $ud, env => { CTL_SOCK_FILE => "/var/run/sense0-sliod3.sock", LNET_NETWORKS => "tcp12(vlan100:3)" } },
		{ name => "sliod4", prog => "sliod", host => "sense1$p", dir => $ud, env => { CTL_SOCK_FILE => "/var/run/sense0-sliod4.sock", LNET_NETWORKS => "tcp12(vlan100:4)" } },
		{ name => "sliod5", prog => "sliod", host => "sense1$p", dir => $ud, env => { CTL_SOCK_FILE => "/var/run/sense0-sliod5.sock", LNET_NETWORKS => "tcp12(vlan100:5)" } },

		{ name => "sliod0", prog => "sliod", host => "sense2$p", dir => $ud, env => { CTL_SOCK_FILE => "/var/run/sense0-sliod0.sock", LNET_NETWORKS => "tcp12(vlan100:0)" } },
		{ name => "sliod1", prog => "sliod", host => "sense2$p", dir => $ud, env => { CTL_SOCK_FILE => "/var/run/sense0-sliod1.sock", LNET_NETWORKS => "tcp12(vlan100:1)" } },
		{ name => "sliod2", prog => "sliod", host => "sense2$p", dir => $ud, env => { CTL_SOCK_FILE => "/var/run/sense0-sliod2.sock", LNET_NETWORKS => "tcp12(vlan100:2)" } },
		{ name => "sliod3", prog => "sliod", host => "sense2$p", dir => $ud, env => { CTL_SOCK_FILE => "/var/run/sense0-sliod3.sock", LNET_NETWORKS => "tcp12(vlan100:3)" } },
		{ name => "sliod4", prog => "sliod", host => "sense2$p", dir => $ud, env => { CTL_SOCK_FILE => "/var/run/sense0-sliod4.sock", LNET_NETWORKS => "tcp12(vlan100:4)" } },
		{ name => "sliod5", prog => "sliod", host => "sense2$p", dir => $ud, env => { CTL_SOCK_FILE => "/var/run/sense0-sliod5.sock", LNET_NETWORKS => "tcp12(vlan100:5)" } },
		{ name => "sliod6", prog => "sliod", host => "sense2$p", dir => $ud, env => { CTL_SOCK_FILE => "/var/run/sense0-sliod6.sock", LNET_NETWORKS => "tcp12(vlan100:6)" } },

		{ name => "sliod0", prog => "sliod", host => "sense3$p", dir => $ud, env => { CTL_SOCK_FILE => "/var/run/sense0-sliod0.sock", LNET_NETWORKS => "tcp12(vlan100:0)" } },
		{ name => "sliod1", prog => "sliod", host => "sense3$p", dir => $ud, env => { CTL_SOCK_FILE => "/var/run/sense0-sliod1.sock", LNET_NETWORKS => "tcp12(vlan100:1)" } },
		{ name => "sliod2", prog => "sliod", host => "sense3$p", dir => $ud, env => { CTL_SOCK_FILE => "/var/run/sense0-sliod2.sock", LNET_NETWORKS => "tcp12(vlan100:2)" } },
		{ name => "sliod3", prog => "sliod", host => "sense3$p", dir => $ud, env => { CTL_SOCK_FILE => "/var/run/sense0-sliod3.sock", LNET_NETWORKS => "tcp12(vlan100:3)" } },
		{ name => "sliod4", prog => "sliod", host => "sense3$p", dir => $ud, env => { CTL_SOCK_FILE => "/var/run/sense0-sliod4.sock", LNET_NETWORKS => "tcp12(vlan100:4)" } },
		{ name => "sliod5", prog => "sliod", host => "sense3$p", dir => $ud, env => { CTL_SOCK_FILE => "/var/run/sense0-sliod5.sock", LNET_NETWORKS => "tcp12(vlan100:5)" } },

		{ name => "sliod0", prog => "sliod", host => "sense4$p", dir => $ud, env => { CTL_SOCK_FILE => "/var/run/sense0-sliod0.sock", LNET_NETWORKS => "tcp12(vlan100:0)" } },
		{ name => "sliod1", prog => "sliod", host => "sense4$p", dir => $ud, env => { CTL_SOCK_FILE => "/var/run/sense0-sliod1.sock", LNET_NETWORKS => "tcp12(vlan100:1)" } },
		{ name => "sliod2", prog => "sliod", host => "sense4$p", dir => $ud, env => { CTL_SOCK_FILE => "/var/run/sense0-sliod2.sock", LNET_NETWORKS => "tcp12(vlan100:2)" } },
		{ name => "sliod3", prog => "sliod", host => "sense4$p", dir => $ud, env => { CTL_SOCK_FILE => "/var/run/sense0-sliod3.sock", LNET_NETWORKS => "tcp12(vlan100:3)" } },
		{ name => "sliod4", prog => "sliod", host => "sense4$p", dir => $ud, env => { CTL_SOCK_FILE => "/var/run/sense0-sliod4.sock", LNET_NETWORKS => "tcp12(vlan100:4)" } },
		{ name => "sliod5", prog => "sliod", host => "sense4$p", dir => $ud, env => { CTL_SOCK_FILE => "/var/run/sense0-sliod5.sock", LNET_NETWORKS => "tcp12(vlan100:5)" } },
		{ name => "sliod6", prog => "sliod", host => "sense4$p", dir => $ud, env => { CTL_SOCK_FILE => "/var/run/sense0-sliod6.sock", LNET_NETWORKS => "tcp12(vlan100:6)" } },

		{ name => "sliod0", prog => "sliod", host => "sense5$p", dir => $ud, env => { CTL_SOCK_FILE => "/var/run/sense0-sliod0.sock", LNET_NETWORKS => "tcp12(vlan100:0)" } },
		{ name => "sliod1", prog => "sliod", host => "sense5$p", dir => $ud, env => { CTL_SOCK_FILE => "/var/run/sense0-sliod1.sock", LNET_NETWORKS => "tcp12(vlan100:1)" } },
		{ name => "sliod2", prog => "sliod", host => "sense5$p", dir => $ud, env => { CTL_SOCK_FILE => "/var/run/sense0-sliod2.sock", LNET_NETWORKS => "tcp12(vlan100:2)" } },
		{ name => "sliod3", prog => "sliod", host => "sense5$p", dir => $ud, env => { CTL_SOCK_FILE => "/var/run/sense0-sliod3.sock", LNET_NETWORKS => "tcp12(vlan100:3)" } },
		{ name => "sliod4", prog => "sliod", host => "sense5$p", dir => $ud, env => { CTL_SOCK_FILE => "/var/run/sense0-sliod4.sock", LNET_NETWORKS => "tcp12(vlan100:4)" } },
		{ name => "sliod5", prog => "sliod", host => "sense5$p", dir => $ud, env => { CTL_SOCK_FILE => "/var/run/sense0-sliod5.sock", LNET_NETWORKS => "tcp12(vlan100:5)" } },

		{ name => "sliod0", prog => "sliod", host => "sense6$p", dir => $ud, env => { CTL_SOCK_FILE => "/var/run/sense0-sliod0.sock", LNET_NETWORKS => "tcp12(vlan100:0)" } },
		{ name => "sliod1", prog => "sliod", host => "sense6$p", dir => $ud, env => { CTL_SOCK_FILE => "/var/run/sense0-sliod1.sock", LNET_NETWORKS => "tcp12(vlan100:1)" } },
		{ name => "sliod2", prog => "sliod", host => "sense6$p", dir => $ud, env => { CTL_SOCK_FILE => "/var/run/sense0-sliod2.sock", LNET_NETWORKS => "tcp12(vlan100:2)" } },
		{ name => "sliod3", prog => "sliod", host => "sense6$p", dir => $ud, env => { CTL_SOCK_FILE => "/var/run/sense0-sliod3.sock", LNET_NETWORKS => "tcp12(vlan100:3)" } },
		{ name => "sliod4", prog => "sliod", host => "sense6$p", dir => $ud, env => { CTL_SOCK_FILE => "/var/run/sense0-sliod4.sock", LNET_NETWORKS => "tcp12(vlan100:4)" } },
		{ name => "sliod5", prog => "sliod", host => "sense6$p", dir => $ud, env => { CTL_SOCK_FILE => "/var/run/sense0-sliod5.sock", LNET_NETWORKS => "tcp12(vlan100:5)" } },
		{ name => "sliod6", prog => "sliod", host => "sense6$p", dir => $ud, env => { CTL_SOCK_FILE => "/var/run/sense0-sliod6.sock", LNET_NETWORKS => "tcp12(vlan100:6)" } },

		{ name => "sliod0", prog => "sliod", host => "sense7$p", dir => $ud, env => { CTL_SOCK_FILE => "/var/run/sense0-sliod0.sock", LNET_NETWORKS => "tcp12(vlan100:0)" } },
		{ name => "sliod1", prog => "sliod", host => "sense7$p", dir => $ud, env => { CTL_SOCK_FILE => "/var/run/sense0-sliod1.sock", LNET_NETWORKS => "tcp12(vlan100:1)" } },
		{ name => "sliod2", prog => "sliod", host => "sense7$p", dir => $ud, env => { CTL_SOCK_FILE => "/var/run/sense0-sliod2.sock", LNET_NETWORKS => "tcp12(vlan100:2)" } },
		{ name => "sliod3", prog => "sliod", host => "sense7$p", dir => $ud, env => { CTL_SOCK_FILE => "/var/run/sense0-sliod3.sock", LNET_NETWORKS => "tcp12(vlan100:3)" } },
		{ name => "sliod4", prog => "sliod", host => "sense7$p", dir => $ud, env => { CTL_SOCK_FILE => "/var/run/sense0-sliod4.sock", LNET_NETWORKS => "tcp12(vlan100:4)" } },
		{ name => "sliod5", prog => "sliod", host => "sense7$p", dir => $ud, env => { CTL_SOCK_FILE => "/var/run/sense0-sliod5.sock", LNET_NETWORKS => "tcp12(vlan100:5)" } },

		{ exec => "sleep", arg => [2] },
		{ prog => "lnrtd", host => "firehose1$p", dir => $d },
		{ prog => "lnrtd", host => "firehose2$p", dir => $d },
		{ prog => "lnrtd", host => "firehose3$p", dir => $d },
		{ prog => "lnrtd", host => "firehose4$p", dir => $d },
	],
);

sub usage {
	die "usage: $0 [-vX] [-x termarg] mode [host[:daemon] ...]\n";
}

my %opts;
getoptv('vXx:', \%opts) or usage;
usage unless @ARGV;
my $mode = shift @ARGV;
my @uspecs = @ARGV;

sub echorun {
	warn @_, "\n" if $opts{v};
	system @_ or warn "$!\n";
}

my $term = "xterm";
$term = $ENV{TERM_PROG} if exists $ENV{TERM_PROG};
my $hostname = `hostname`;

die "$mode: bad mode\n" unless exists $dep{$mode};

my $found = 0;
foreach my $spec (@{ $dep{$mode} }) {
	if ($spec->{exec}) {
		next if @uspecs && $spec->{exec} eq "sleep";
		echorun $spec->{exec}, @{ $spec->{arg} };
		next;
	}
	if (@uspecs) {
		$found = 0;
		foreach my $uspec (@uspecs) {
			my ($h, $n) = split $uspec, /:/;
			$n = $spec->{name} unless $n;
			if ($n eq $spec->{name} &&
			    $spec->{host} =~ /^\Q$h\E/) {
				$found = 0;
				last;
			}
		}
		next unless $found;
	}
	unless (exists $opts{X} or $spec->{host} eq $hostname) {
		warn "$spec->{host} is not this host, skipping\n";
		next;
	}
	$spec->{cmds} = "" unless exists $spec->{cmds};
	my $init = <<EOF;
		export PSC_SYSLOG_info=1
		export PSC_LOG_LEVEL=warn
		export PSC_LOG_LEVEL_info=info
		export PSC_LOG_FILE=$spec->{dir}/$mode.s2/log/$spec->{name}.$spec->{host}/%t
		export CONFIG_FILE=$spec->{dir}/$mode.s2/slcfg
		export SHELL=/bin/bash
		export GDBHISTFILE=`which $spec->{prog}`.gdbhist
		ulimit -n 100000

		mkdir -p \$(dirname \$PSC_LOG_FILE)
		cd "$spec->{dir}/src/p"

		$spec->{init}

		tmpfile=/tmp/.gdbcmd.\$RANDOM
		(
			echo set history save on
			echo set history size 10000
			echo set confirm off
			echo set height 0
			echo set args
			echo ru
		) > \$tmpfile
		gdb -x \$tmpfile -q $spec->{prog}
EOF
	my $screen = "screen -A -x -R";
	my $name = "$mode.$spec->{name}";

	if ($opts{X}) {
		my @xtargs;
		push @xtargs, @{ $opts{x} } if $opts{x};
		push @xtargs,
		    qw(-xrm XTerm*allowTitleOps:false),
		    "-title", "$spec->{host}: $name" if $term =~ /xterm/;
		if (fork) {
			exec $term, @xtargs, qw(-e ssh -t), $spec->{host},
			    "sudo", $screen, "-S", $name,
			    "sh", "-c", "'$init'" or die "exec: $!\n";
		}
	} else {
		exec $screen, "-S", $name, "sh", "-c", $init or
		    die "exec: $!\n";
	}
}

warn "host/daemon spec produced no matches" if @uspecs && !$found;
